name: GitHub Pages action
on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      # Any prerequisite steps
      - uses: actions/checkout@master

      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
